/*
	Error code
*/

#ifndef OPPVS_ERROR_HPP
#define OPPVS_ERROR_HPP

namespace oppvs {
	typedef enum ERRS_VIDEO_CAPTURE {
		ERR_VIDEO_CAPTURE_NONE,
		ERR_VIDEO_CAPTURE_SESSION_INIT_FAILED,
		ERR_VIDEO_CAPTURE_INPUT_DEVICE_FAILED,
		ERR_VIDEO_CAPTURE_OUTPUT_DEVICE_FAILED
	} error_video_capture_t;

	enum ERRS_ENCODING {
		ERRS_ENCODING_OK,
		ERRS_ENCODING_INIT_FAILED
	};

	enum ERRS_DECODING {
		ERRS_DECODING_OK,
		ERRS_DECODING_INIT_FAILED
	};

}

#endif